# Generated by Django 5.0.1 on 2024-05-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pyment_status',
            field=models.BooleanField(default=False),
        ),
    ]
