# Generated by Django 5.0.1 on 2024-05-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cart_pyment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pyment_status',
        ),
    ]
