# Generated by Django 5.0.1 on 2024-05-08 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
