# Generated by Django 5.0.1 on 2024-05-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_order_address_alter_order_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pyment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
